# services:
#   jaeger:
#     networks:
#       - backend
#     image: jaegertracing/all-in-one:latest
#     volumes:
#       - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
#     command: --query.ui-config /etc/jaeger/jaeger-ui.json
#     environment:
#       - COLLECTOR_OTLP_ENABLED=true
#       - METRICS_STORAGE_TYPE=prometheus
#       - PROMETHEUS_SERVER_URL=http://prometheus:9090
#     ports:
#       # https://www.jaegertracing.io/docs/2.1/apis/#default-ports
#       - 16686:16686
#       - 16685:16685
#       - 4317:4317
#       - 4318:4318
#       - 6831:6831/udp
#   otel_collector:
#     networks:
#       - backend
#     image: otel/opentelemetry-collector-contrib:latest
#     volumes:
#       - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
#       # - "./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml"
#     command: --config /etc/otelcol/otel-collector-config.yml
#     # command: --config /etc/otelcol-contrib/config.yaml
#     ports:
#       - "14278:14278"
#       # - 4318:4318
#     depends_on:
#       - jaeger
#       - prometheus
#   prometheus:
#     networks:
#       - backend
#     image: prom/prometheus:latest
#     volumes:
#       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
#     ports:
#       - "9090:9090"
# networks:
#   backend:

services:
  jaeger:
    networks:
      backend:
        # This is the host name used in Prometheus scrape configuration.
        aliases: [spm_metrics_source]
    image: jaegertracing/jaeger:${JAEGER_IMAGE_TAG:-latest}
    volumes:
      - "./config-spm.yaml:/etc/jaeger/config.yml"
    command: ["--config", "/etc/jaeger/config.yml"]
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
  prometheus:
    networks:
      - backend
    image: prom/prometheus:v3.0.1
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
networks:
  backend:
volumes:
  prometheus-data: {}